services:
  xorot:
    build:
      context: "."
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "127.0.0.1:4242:4242"
